name: Desplegar RestoPub a GitHub Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4 # GitHub gestiona la compatibilidad interna aquí

      - name: Configurar Pages
        uses: actions/configure-pages@v5

      - name: Subir el archivo index.html
        uses: actions/upload-pages-artifact@v3 # Esta versión interna ya mitiga el aviso de carga
        with:
          path: '.'

      - name: Desplegar a GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
